apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth

spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: auth
          image: 009160064216.dkr.ecr.us-west-1.amazonaws.com/video-to-mp3/auth
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: auth-secrets